config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('gazovik.users.urls', namespace='users')),
    url(r'^catalog/', include('gazovik.webapp.urls', namespace='catalog')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

gazovik/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

gazovik/webapp/urls.py
from django.conf.urls import url, include
# from rest_framework import routers
# import api
import gazovik.webapp.views as views

# router = routers.DefaultRouter()
# router.register(r'tovar', api.TovarViewSet)
# router.register(r'category', api.CategoryViewSet)


# urlpatterns = (
#     # urls for Django Rest Framework API
#     url(r'^api/v1/', include(router.urls)),
# )

urlpatterns = [
    # urls for Tovar
    url(r'^tovar/$', views.TovarListView.as_view(), name='list'),
    url(r'^tovar/(?P<slug>\S+)/$', views.TovarDetailView.as_view(), name='detail'),
    # url(r'^webapp/tovar/update/(?P<slug>\S+)/$', views.TovarUpdateView.as_view(), name='webapp_tovar_update'),

    # urls for Category
    url(r'^category/$', views.CategoryListView.as_view(), name='category_list'),
    # url(r'^webapp/category/create/$', views.CategoryCreateView.as_view(), name='webapp_category_create'),
    url(r'^category/(?P<slug>\S+)/$', views.CategoryDetailView.as_view(), name='webapp_category_detail'),
    # url(r'^webapp/category/update/(?P<slug>\S+)/$', views.CategoryUpdateView.as_view(), name='webapp_category_update'),
]

gazovik/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

gazovik/webapp/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from transliterate import translit, get_available_language_codes
from django.template.defaultfilters import slugify


class Tovar(models.Model):
    """docstring for Tovar."""
    slug = models.SlugField(max_length=100, unique=True, blank=True)
    name = models.CharField(blank=False, max_length=100)
    description = models.TextField(blank=True, max_length=100)
    haracteristiki = models.TextField(blank=True, max_length=100)
    image = models.ImageField(upload_to="upload/images/", blank=True)
    # height_field=640, width_field=360,
    image_mini = models.ImageField(upload_to="upload/images/thumb/", blank=True)
    price = models.IntegerField(blank=True, null=True)
    category = models.ForeignKey('Category', db_index=True)
    data = models.DateTimeField(default=timezone.now)

    best = models.BooleanField(default=False)

    def __str__(self):
        return str('[{}] {}').format(self.name, self.description)

    def save(self):
        if not self.slug:
            self.slug = slugify(translit(self.name, 'ru', reversed=True))
        super(Tovar, self).save()

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})

    # def get_absolute_url(self):
    #     return reverse('webapp_tovar_detail', args=(self.slug,))


class Category(models.Model):
    """docstring for Category."""
    name = models.CharField(blank=False, max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return str('[{}] {}').format(self.name, self.slug)

gazovik/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

gazovik/webapp/views.py
from django.views.generic import DetailView, ListView
from .models import Tovar, Category
# from .forms import TovarForm, CategoryForm


class TovarListView(ListView):
    model = Tovar

class TovarDetailView(DetailView):
    model = Tovar

class CategoryListView(ListView):
    model = Category

class CategoryDetailView(DetailView):
    model = Category

gazovik/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

gazovik/templates/base.html
{% load static i18n compress%}
<!DOCTYPE HTML>
<html class="no-js">

<head>
  <!-- Basic Page Needs
  ================================================== -->
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>{% block title %}Gazovik{% endblock title %}</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">
  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
  <meta name="format-detection" content="telephone=no">
  <!-- CSS
  ================================================== -->
  {% block css %}
  {% compress css %}

  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
  {# <link href="{% static 'css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css">#}
  <link href="{% static 'plugins/mediaelement/mediaelementplayer.css' %}" rel="stylesheet" type="text/css">
  {# <link href="{% static 'css/rtl.css' %}" rel="stylesheet" type="text/css">#}
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'plugins/prettyphoto/css/prettyPhoto.css' %}" rel="stylesheet" type="text/css">
  <!--[if lte IE 8]><link rel="stylesheet" type="text/css" href="css/ie8.css" media="screen" /><![endif]-->
  <!-- Color Style -->
  <link href="{% static 'colors/color1.css' %}" rel="stylesheet" type="text/css">


  <link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'slick/slick-theme.css' %}"/>



  {% endcompress %}
  {% endblock %}
  <!-- SCRIPTS
  ================================================== -->
  <script src="{% static 'js/modernizr.js' %}"></script>
  <!-- Modernizr -->
</head>


<body>
<!--[if lt IE 7]>
	<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->
<div class="body">
  <!-- Start Site Header -->
  <header class="site-header">
    <div class="topbar">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-6 col-xs-8">
            <h1 class="logo"> <a href="/"><img src="{% static 'images/logo.png' %}" alt="Logo"></a> </h1>
          </div>
          <div class="col-md-8 col-sm-6 col-xs-4 text-right">
                     <p style="margin-bottom: 0px;"><b>Тел.</b>: <span class="lead red"> +7 (3473) 25-00-84, 8-963-894-55-84</span></p>
          <small><b>E-mail:</b> <span class=""> magazin-gazovik@hotmail.com</span></small> <br>
          <small><b>Адрес:</b> <span class=""> г.Стерлитамак, ул.Худайбердина, 76</span></small>
            <a href="#" class="visible-sm visible-xs menu-toggle"><i class="fa fa-bars"></i></a> </div>
        </div>
      </div>
    </div>
    <div class="main-menu-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <nav class="navigation">
              <ul class="sf-menu">

                <li><a href="{% url 'catalog:list' %}">Товар</a>

                </li>
                <li><a href="{% url 'catalog:category_list' %}">Категория</a>

                </li>
                <li><a href="{% url 'about' %}">About</a>

                </li>
                <li><a href="{% url 'home' %}">Gazovik</a>

              	</li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End Site Header -->
  <!-- Start Nav Backed Header -->
  <div class="nav-backed-header parallax" style="background-image:url('/static/images/gas-stove-1776648_1920.jpg');">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">{{ page.title }}</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <!-- End Nav Backed Header -->
  <!-- Start Page Header -->
  <div class="page-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>{{ page.title }}{{ section.title }}{{ title }}{{ article.title }}  {{ title.super }}{{ entry.title }}{{ page.name }}</h1>
        </div>
      </div>
    </div>
  </div>
  <!-- End Page Header -->
  <!-- Start Content -->
  <div class="main" role="main">
    <div id="content" class="content full">
      <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Добро пожаловать</p>
      {% endblock content %}

    </div> <!-- /container -->


  </div>
  </div>
  <!-- Start Footer -->
  <footer class="site-footer">
  <div class="container">
  <div class="row">
    <!-- Start Footer Widgets -->
    <div class="col-md-4 col-sm-4 widget footer-widget">
      <h4 class="footer-widget-title">О нашем магазине</h4>
      <img src="{% static 'images/logo.png' %}" alt="Logo">
      <div class="spacer-20"></div>
      <p>Мы предлагаем газовое оборудование для учёта, обогрева, комфорта и для безопасного использования в квартирах и частных домах.</p>
    </div>

<!--
    <div class="col-md-4 col-sm-4 widget footer-widget">
      <h4 class="footer-widget-title">Blogroll</h4>
      <ul>
        <li><a href="index.html">Church Home</a></li>
        <li><a href="about.html">About Us</a></li>
        <li><a href="events.html">All Events</a></li>
        <li><a href="sermons.html">Sermons Archive</a></li>
        <li><a href="blog-masonry.html">Our Blog</a></li>
      </ul>
    </div>
    <div class="col-md-4 col-sm-4 widget footer-widget">
      <h4 class="footer-widget-title">Our Church on twitter</h4>
      <ul class="twitter-widget" data-tweets-count="1">
      </ul>
    </div> -->


  </div>
  </div>
  </footer>
  <footer class="site-footer-bottom">
  <div class="container">
  <div class="row">
    <div class="copyrights-col-left col-md-6 col-sm-6">
      <p>&copy; 2014 NativeChurch. All Rights Reserved</p>
    </div>
    <div class="copyrights-col-right col-md-6 col-sm-6">
      <div class="social-icons"> <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a> <a href="https://twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a> <a href="http://www.pinterest.com/" target="_blank"><i class="fa fa-pinterest"></i></a> <a href="https://plus.google.com/" target="_blank"><i class="fa fa-google-plus"></i></a> <a href="http://www.pinterest.com/" target="_blank"><i class="fa fa-youtube"></i></a> <a href="#"><i class="fa fa-rss"></i></a> </div>
    </div>
  </div>
  </div>
  </footer>
  <!-- End Footer -->
  <a id="back-to-top"><i class="fa fa-angle-double-up"></i></a>
  </div>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="http://code.jquery.com/jquery-3.2.1.min.js" ></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      {% compress js%}
      {% block javascript_add %}
      {% endblock javascript_add %}

      {% endcompress %}

    {% endblock javascript %}


  </body>
</html>

gazovik/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

gazovik/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

gazovik/templates/pages/about.html
{% extends "base.html" %} {% load static %} {% block content %}

<div class="span4">

  <address>

  <p><span class="lead">+7 (3473) 25-00-84, 8-963-894-55-84</span></p>


 <p><i class="fontello icon-users"></i> <b> Мы работаем:</b> ПН-ПТ с 9 до 19, СБ с 10 до 18, ВС  с 10 до 17</p>
 <p><i class="fontello icon-home"></i> <b>Адрес:</b> 453124, Республика Башкортостан, г. Стерлитамак, ул. Худайбердина, 76 (около остановки "Горгаз")</p>
 <p><i class="fontello icon-mail-alt"></i> <b>E-mail:</b> magazin-gazovik@hotmail.com </p>





</address>


</div>

<a class="dg-widget-link" href="http://2gis.ru/sterlitamak/firm/7600352652165877/center/55.949872,53.625611/zoom/16?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=bigMap">Посмотреть на карте Стерлитамака</a>
<div class="dg-widget-link"><a href="http://2gis.ru/sterlitamak/center/55.949872,53.625611/zoom/16/routeTab/rsType/bus/to/55.949872,53.625611╎Газовик, магазин газового оборудования?utm_medium=widget-source&utm_campaign=firmsonmap&utm_source=route">Найти проезд до Газовик, магазин газового оборудования</a></div>
<script
  charset="utf-8" src="https://widgets.2gis.com/js/DGWidgetLoader.js"></script>
  <script charset="utf-8">
    new DGWidgetLoader({
      "width": 1000,
      "height": 400,
      "borderColor": "#a3a3a3",
      "pos": {
        "lat": 53.625611,
        "lon": 55.949872,
        "zoom": 16
      },
      "opt": {
        "city": "sterlitamak"
      },
      "org": [{
        "id": "7600352652165877"
      }]
    });
  </script><noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript> {% endblock %}

gazovik/templates/pages/home.html
{% extends "base.html" %}
{% load static category %}

{% block content %}

<h2 class="">Газовые плиты</h2>
<div class="well gallery-slick" style="margin-bottom:120px;  ">
  {% category_slick 1 10 %}
</div>

<h2>Котлы</h2>
<div class="well gallery-slick" style="margin-bottom:120px;  ">
  {% category_slick 4 10 %}
</div>

<br />


{% endblock %}


{% block javascript_add %}

<script src="{% static 'slick/slick.min.js' %}"></script> <!-- Jquery Timer -->

<script type="text/javascript">
   $(document).ready(function(){
     $('.gallery-slick').slick({

         centerMode: true,
         adaptiveHeight: true,
         centerPadding: '60px',
        //  slidesToShow: 10,
         variableWidth: true,
         dots: true,
         focusOnSelect: true,
        //  slidesToShow: 5,
        slidesToScroll: 3,
        autoplay: true,
        autoplaySpeed: 2000,

         responsive: [
           {
             breakpoint: 768,
             settings: {
               arrows: false,
               centerMode: true,
               centerPadding: '40px',
               slidesToShow: 5
             }
           },
           {
             breakpoint: 480,
             settings: {
               arrows: false,
               centerMode: true,
               centerPadding: '40px',
               slidesToShow: 3
             }
           }
         ]

     });
   });
 </script>

{% endblock javascript_add %}

gazovik/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

gazovik/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

gazovik/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}

gazovik/webapp/templates/webapp/category_detail.html
{% extends "base.html" %}
{% load static category %}

{% block content %}


<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>slug</td><td>{{ object.slug }}</td></tr>
<tr><td>id</td><td>{{ object.id }}</td></tr>
</table>

{% category_list object.id 10 %}


{% endblock %}

gazovik/webapp/templates/webapp/category_detail2.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'webapp_category_list' %}">Category Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>slug</td><td>{{ object.slug }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Category</a>

{% endblock %}

gazovik/webapp/templates/webapp/category_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'webapp_category_list' %}">Category Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

gazovik/webapp/templates/webapp/category_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>slug</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{% url 'catalog:webapp_category_detail' object.slug %}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.slug }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

gazovik/webapp/templates/webapp/category_list2.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>slug</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{% url 'catalog:detail' object.slug %}">{{object}}</a></td>
    <td>{{ object.name }}</td>
    <td>{{ object.slug }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}

gazovik/webapp/templates/webapp/tags/tovar_list.html
<!-- Start roducts-list-->
{% for object in category %}
  {% include "webapp/tovar_item.html" %}
{% endfor %}

gazovik/webapp/templates/webapp/tovar_detail2.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'catalog:list' %}">Назад</a></p>
<table class="table">
<tr><td>slug</td><td>{{ object.slug }}</td></tr>
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>description</td><td>{{ object.description }}</td></tr>
<tr><td>image</td><td>{{ object.image.url }}</td></tr>
<tr><td>price</td><td>{{ object.price }}</td></tr>
<tr><td>data</td><td>{{ object.data }}</td></tr>
</table>

{% endblock %}

gazovik/webapp/templates/webapp/tovar_item.html
{% load static %}

  <div class="col-md-3 col-sm-6" >
    	<div class="shop-item">
      	<div class="product-image thumbnail">
          	<a href="{% url 'catalog:detail' object.slug %}">
              <img src="/media/{{ object.image }}" class='img-responsive'/></a>

         	</div>
      	<div class="product-details">
        		<b style="height:200px">
              <a href="{% url 'catalog:detail' object.slug %}" >{{ object.name }}</a></b>
        </div>
    	</div>

  </div>

gazovik/webapp/templates/webapp/tovar_item_slick.html
<div>

  <img src="/media/{{ object.image }}" />

  <span style="margin-right: 10px;">
    <a href="{% url 'catalog:detail' object.slug %}" style='width:50px'>{{ object.slug }}</a></b>
  </span>

</div>

gazovik/webapp/templates/webapp/tovar_list2.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>slug</td>
    <td>name</td>
    <td>description</td>
    <td>image</td>
    <td>price</td>
    <td>data</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{% url 'catalog:detail' object.slug %}">{{object}}</a></td>
    <td>{{ object.slug }}</td>
    <td>{{ object.name }}</td>
    <td>{{ object.description }}</td>
    <td>{{ object.image }}</td>
    <td>{{ object.price }}</td>
    <td>{{ object.data }}</td>
</tr>
{% endfor %}
</table>
{% endblock %}